service: exiftool-golang-lambda-layer

provider:
  name: aws
  region: eu-west-1
  runtime: go1.x

layers:
  exiftool:
    path: layer
    description: exiftool with go1.x
    compatibleRuntimes:
      - go1.x
    licenseInfo: MIT License
